language: node_js
node_js:
- '0.10'
- 4.1.1
before_script:
- npm install -g gulp
script: gulp
deploy:
  provider: heroku
  api_key:
    secure: HYW4TPtgU5ggmbnG1XwIiyv9RPBQb4wcNkueZpBraMkfaVH/VM78sbQMiJJ9ayhgpMZB+pqcvlG5iAsaud3v2wU5GkIbtuAxcSn2/rSZMdDYSSZJ96vA6wmem81fGhPV2pT6quGgNgZ5AanRVuwlDOwSVyVsHArlGl7KvNS4aMYwf5qfpvNR4R3IAGOo+KUm05JYR1K1iuLmo05ukFf1cJJWLB4EI4Oqi8ZD9fNFX/WU9ZfYVA7rOsMCriHX9a+oxazECzw2RVaieChJLfr6nhbH84uv6c7/y59+apR2cZtn6qxyw7nyueJVNVnoFj5MMG83CAZ0UfrEzZzD17rXE4IKfgu2GZNwQHyNJcOiTAvCSxV7VM9JFJTG7Svs6ZgmLse/rX2OBHBM598mPWsD8Q8O+GZ7kbHPJegFhqtLqDpqkvAN6rZ3fSVTq4zgto8XCCYyQiv1yjAMz8HmwEyPlupYiT9K31f08xKQpVrli8xkC5Ak2MmoHWPsTPOwNVgis0uwJGClWyO9MmriuGqCzCyuyKxqQjdRSdepRWGO47CpyBSAUHTdxtNQ0haMYeas+cSObe0lDXBctqwfldob66lBTiRq6gk1pxyXhGBvDQv01Ur1DS7/0+oc0/Sp/Bnd1PJcAf+rgko31DyiiaRNLwTdDZsCogeGIOFUha/P/ic=
  app: gotta-go-sf
  on:
    repo: amused-rutabega/thesecrettoiletsofsf
    branch: master
